### PR TITLE
added the database schema

### LINKED ISSUE #35: Create a Schema/UML for the model

### PR DESCRIPTION
**Pull request by Fahid-Mannan**
This is the scheme for the first milestone of the Model #35

### CODE REVIEW

**Review by TaylorAbraham — APPROVED** [review]
Simple change. Looks good.

**Comment by Fahid-Mannan** [comment]
> Simple change. Looks good.

@TaylorAbraham I am assuming you were able to verify the schema with the actual model within the code.

**Comment by TaylorAbraham** [comment]
> > Simple change. Looks good.
> 
> @TaylorAbraham I am assuming you were able to verify the schema with the actual model within the code.

Yup! Checked it when Michael sent it over, it matches the structure I'd expect to see.

**Review by JacksonSchoe — APPROVED** [review]
Looks great. Nice work

**Review by TaylorAbraham — APPROVED** [review]
Reviewed the new changes, looks good.

**Pull request merged**
